steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-east4-docker.pkg.dev/omega-ability-466020/my-repo/olci-api',
        '.'
      ]

  # Step 2: Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', us-east4-docker.pkg.dev/omega-ability-466020/my-repo/olci-ap]

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run',
        'deploy',
        'olci-api',
        '--image',
        'us-east4-docker.pkg.dev/omega-ability-466020/my-repo/olci-api',
        '--region',
        'us-east4',
        '--platform',
        'managed',
        '--allow-unauthenticated'
      ]

# Optional: specify logs bucket if needed
logsBucket: 'gs://omega-ability-466020-k9-cloudbuild-logs'